
# .github/workflows/deploy_prod.yml
name: Deploy Prod to EC2

#jab bhi main branch pe koi push ho tab run jobs
on:
  push:
    branches:
      - main
  workflow_dispatch:

#
jobs:
  deploy:
    name: Deploy Production Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Prod EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ubuntu
          key: ${{ secrets.PROD_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/auth_backend

            if [ ! -d .git ]; then
              git clone https://github.com/SanketGamer/auth_backend.git .
            fi

            git fetch origin
            git checkout main
            git pull origin main

            # docker compose down
            # docker compose up -d --build

            # docker image prune -f